name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - name: Run tests
      run: make test
    - name: Run coverage
      run: make cover

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: |
        make docker
        docker build -t girc .
    - name: Tag and push image
      run: |
        commit=$(git rev-parse HEAD)
        docker tag girc:latest ghcr.io/${{ github.repository }}/app:latest
        docker tag girc:latest "ghcr.io/${{ github.repository }}/app:${commit}"
        docker push ghcr.io/${{ github.repository }}/app:latest
        docker push "ghcr.io/${{ github.repository }}/app:${commit}"
